// Проверка реального ввода и панели; Playwright берётся из внешнего QA-окружения.
const assert = require('node:assert/strict');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || '/tmp/bonk-tuglab-ui/node_modules/playwright');
(async () => {
 const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true });
 const width = Number(process.env.TUGLAB_WIDTH || 1024);
 try {
 const page = await browser.newPage({ viewport: { width, height: Number(process.env.TUGLAB_HEIGHT || 600) } });
 const errors = [], api = [];
 page.on('pageerror', e => errors.push(e.message));
 page.on('request', r => { if (r.resourceType() === 'fetch' || r.resourceType() === 'xhr' || r.resourceType() === 'websocket') api.push(r.url()); });
 await page.goto(process.env.TUGLAB_URL || 'http://localhost:5174/tuglab.html');
 await page.waitForFunction(() => window.__bonkLab);
 assert.equal(await page.evaluate(() => !!window.__bonkLab.getState().towing), true);
 await page.getByRole('button', { name: 'Пауза', exact: true }).click();
 const beforeStep = await page.evaluate(() => window.__bonkLab.getState().startCountdown);
 await page.getByRole('button', { name: 'Step', exact: true }).click();
 const afterStep = await page.evaluate(() => window.__bonkLab.getState().startCountdown);
 assert.ok(Math.abs((beforeStep - afterStep) - 1 / 60) < 1e-9);
 assert.equal(await page.evaluate(() => window.__bonkLab.getState().towing.paused), true);
 await page.getByRole('button', { name: 'Продолжить', exact: true }).click();
 await page.locator('#lab-canvas').click({ position: { x: 200, y: 200 } });
 await page.keyboard.down('w');
 assert.equal(await page.evaluate(() => window.__labInput.getState().y), -1);
 await page.getByLabel('Масса B / A', { exact: true }).focus();
 assert.equal(await page.evaluate(() => window.__labInput.getState().magnitude), 0);
 await page.keyboard.up('w');
 const seedBefore = await page.evaluate(() => JSON.stringify(window.__bonkLab.getState().arena.obstacles));
 await page.getByLabel('Масса B / A', { exact: true }).fill('2');
 assert.equal(await page.evaluate(() => window.__bonkLab.params['tow.massRatio']), 2);
 await page.getByLabel('Жёсткость k').fill('');
 assert.equal(await page.evaluate(() => window.__bonkLab.params['tow.stiffness']), 1250);
 assert.ok(await page.getByRole('alert').count());
 await page.getByLabel('Жёсткость k').fill('2400');
 assert.equal(await page.evaluate(() => window.__bonkLab.params['tow.stiffness']), 2400);
 assert.equal(await page.evaluate(() => JSON.stringify(window.__bonkLab.getState().arena.obstacles)), seedBefore);
 await page.getByRole('button', { name: 'Restart', exact: true }).click();
 assert.equal(await page.evaluate(() => window.__labInput.getState().magnitude), 0);
 await page.getByRole('button', { name: 'Расцепить', exact: true }).click();
 assert.equal(await page.evaluate(() => window.__bonkLab.getState().towing.coupling.connected), false);
 await page.getByRole('button', { name: 'Сцепить', exact: true }).click();
 assert.equal(await page.evaluate(() => window.__bonkLab.getState().towing.coupling.connected), true);
 assert.equal(await page.getByRole('button', { name: 'Экспорт', exact: true }).count(), 0);
 const rects = await page.evaluate(() => ({ canvas: document.querySelector('canvas').getBoundingClientRect().toJSON(), toolbar: document.querySelector('.lab-toolbar').getBoundingClientRect().toJSON(), buttons: [...document.querySelectorAll('.tug-actions button')].map(b => b.getBoundingClientRect().toJSON()) }));
 assert.ok(rects.canvas.top >= rects.toolbar.bottom);
 assert.ok(rects.buttons.every(r => r.width >= 48 && r.height >= 48));
 await page.waitForFunction(() => window.__bonkLab.getState().startCountdown <= 0);
 await page.getByRole('button', { name: 'Пауза', exact: true }).click();
 await page.screenshot({ path: `/tmp/task4-desktop-${width}.png` });
 await page.getByRole('button', { name: 'Продолжить', exact: true }).click();
 const cdp = await page.context().newCDPSession(page);
 await page.locator('#lab-canvas').click({ position: { x: 200, y: 200 } });
 await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: 200, y: rects.canvas.top + 180 }] });
 await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: 200, y: rects.canvas.top + 80 }] });
 assert.equal(await page.evaluate(() => window.__labInput.getState().y), -1);
 assert.equal(await page.evaluate(() => window.__labInput.getState().isTouch), true);
 await cdp.send('Input.dispatchTouchEvent', { type: 'touchCancel', touchPoints: [] });
 assert.equal(await page.evaluate(() => window.__labInput.getState().magnitude), 0);
 await page.mouse.move(400, rects.canvas.top + 180); await page.mouse.down();
 assert.ok(await page.evaluate(() => window.__labInput.getState().magnitude > 0));
 await page.evaluate(() => window.dispatchEvent(new Event('blur')));
 assert.equal(await page.evaluate(() => window.__labInput.getState().magnitude), 0);
 assert.equal(await page.evaluate(() => window.__bonkLab.getState().towing.paused), true);
 await page.mouse.up();
 await page.getByRole('button', { name: 'Rnd', exact: true }).click();
 assert.notEqual(await page.evaluate(() => JSON.stringify(window.__bonkLab.getState().arena.obstacles)), seedBefore);
 await page.getByLabel('Seed', { exact: true }).fill('123');
 assert.equal(await page.getByLabel('Seed', { exact: true }).inputValue(), '123');
 const densityBefore = await page.evaluate(() => window.__bonkLab.params['arena.objectDensity']);
 await page.getByLabel('Насыщенность арены').focus();
 await page.getByLabel('Насыщенность арены').press('ArrowRight');
 assert.ok(await page.evaluate(v => window.__bonkLab.params['arena.objectDensity'] > v, densityBefore));
 await page.getByLabel('Пресет движения').selectOption('1');
 assert.equal(await page.getByLabel('Пресет движения').inputValue(), '1');
 assert.equal(await page.evaluate(() => window.__bonkLab.params['tow.massRatio']), 2);
 assert.deepEqual(errors, []); assert.deepEqual(api, []);
 console.log('PASS real UI: pause/step/restart/capture/keyboard/focus/numeric/map/mouse/touch/blur/layout/no API');
 } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exit(1); });
